### ISSUE TITLE
有几个问题想探讨一下

### ISSUE THREAD

**Issue by Jemair** [hiyangguo/webpack-mutiple-theme-bundle-css-demo#1]
大佬  我现在想要达成目标是在打包时根据主题色的变量自动生成多个.css文件
看了你的demo觉得这种实现思路可取 但是有几个问题想要看看你有没有比较好的解决方案

1. 现代的react项目一般.less文件都是分散于各个文件夹 这样你的这种实现思路就需要在每一个主题中手动引入每一个[component].less 这样显然工作量巨大并且不够优雅

1. 当在react中使用cssModule时因为改变了文件的路径 导致类名会发生变化

目前我考虑的解决方案是在less-loader中通过控制`modifyVars`字段 引入不同的theme.json文件 来达到控制less变量的效果 但是出现的问题是同一个文件不能被less多次打包

**Comment by hiyangguo** [comment]
@Jemair  之前我也想用 `modifyVars` 控制主题色，但是由于 `less-loader` 的限制，并不能生成多套 css。要么就要多次执行 build 。所以才想到了这个解决方案。这里的 `[themes].less` 实际上依然可以用脚本生成。就是在 build 前先执行脚本读取 `json` 配置生成一堆的 `[themes].less` 并重写 `themes.js` 中的内容。就好了。不用手动写。

然后你说的第二个问题，我还没有遇到过。能解释一下么？

**Comment by Jemair** [comment]
cssmodules不是会根据namespace生成classname嘛   一般是在每一个react组件中引入component.less  这样的话就不能直接在入口处引入一个theme.less的包了 

不过我们重新思考了一下  修改主题色也就是几行代码的事情  theme-a.less和theme-b.less的代码相似率可能达到90%以上  其实打包在一起也不影响  没必要花费这么多心思

目前的解决方案是如果检测到夜间模式就在body上加#night 然后在组件各自的样式底部对颜色进行覆写  代码形式上类似媒体查询

**Comment by hiyangguo** [comment]
@Jemair 实际上夜间模式和多主题 不算完全是一个事儿。多主题 一般只是改个主色。但夜间模式，因为背景色变成了黑色。所以要调整很多东西。也就是说红色、蓝色主题也可以有自己的夜间模式。 另外使用 cssmodules 的话要在 `ExtractTextPlugin` 中配置一下。就好了。 不过还是建议在一个统一的` index.less `中写好
```less
@import "./main.less"
// 组件样式
@import "./Components/Table/index.less"
@import "./Components/Picker/index.less"
```
然后主题文件这样写
```
@import "../index.less";
// 不同文件的基色不同
@base-color:'##34c3ff';
```
然后就好了。我回头空了更新一下这边的代码吧

主题色改变讲道理处理 基色之外什么都不用更改。 当然不排除需要在不同主色有一些调整，这个也可以配置在`json`中，生成脚本的时候自己写一下就好了。非常简单。

**Comment by hiyangguo** [comment]
@Jemair 我更新了代码，现在主题是读取`themes.config.js`的配置生成的。我的演示中只是重写了`base-color`，但可以任意重写变量。
